baseURL = 'https://KDZZZZZZ.github.io'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Oops'
theme = 'PaperMod'

# Search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true  # Use inline styles for syntax highlighting
    style = "friendly" # Use a light theme (friendly, tango, trac, colorful)
    tabWidth = 4

[params]
  author = "Oops"
  defaultTheme = "light"  # Changed to light to match new design
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  
  # Profile Mode Settings
  [params.profileMode]
    enabled = true
    title = "Oops"
    subtitle = "The only limit to our realization of tomorrow will be our doubts of today."
    imageUrl = "/images/27dd0570-1c1b-42af-8a83-a564c7b6ba87.png"
    imageTitle = "my image"
    imageWidth = 150
    imageHeight = 150

  # Social Icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/KDZZZZZZ"

  # Footer Information
  [params.footer]
  since = 2024
  poweredBy = true

  # Home Background
  [params.assets]
  disableHLJS = true
  favicon = "/favicon.ico"
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40
